{% set name = "climix" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/climix-{{ version }}.tar.gz
  sha256: 6875f2958f657b2e5160619eefeabfc24a534f585496b8f32913b32defa041f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - climix = climix.main:main
    - climix-index-docs = climix.index_docs:main

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - bottleneck
    - cftime
    - cf-units
    - dask >=2023.1.0
    - dask-jobqueue
    - dask-mpi
    - importlib-metadata >=4.4
    - isodate
    - netcdf4
    - numba
    - numpy
    - pandas
    - psutil
    - pyxdg
    - pyyaml
    - regex
    - sentry-sdk
    - scitools-iris >=3,<4
    - sparse

test:
  imports:
    - climix
  commands:
    - pip check
    - climix --help
  requires:
    - pip

about:
  home: https://git.smhi.se/climix/climix
  summary: A climate index package
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://git.smhi.se/climix/climix
  doc_url: https://climix.readthedocs.io

extra:
  recipe-maintainers:
    - zklaus
